export const LOGIN_USER_PENDING='LOGIN_USER_PENDING';
export const LOGIN_USER_SUCCESS='LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED='LOGIN_USER_FAILED';


export const REGISTER_USER_PENDING='REGISTER_USER_PENDING';
export const REGISTER_USER_SUCCESS='REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED='REGISTER_USER_FAILED';

export const LOGOUT_USER_PENDING='LOGOUT_USER_PENDING';
export const LOGOUT_USER_SUCCESS='LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILED='LOGOUT_USER_FAILED';

export const PLEASE_REGISTER_FIRST='PLEASE_REGISTER_FIRST';
export const LAST_SELLER_ITEM_FETCHED='LAST_SELLER_ITEM_FETCHED';